### ISSUE TITLE
OSX repaint bug in 3.2.0

### ISSUE THREAD

**Issue by JulianSmart** [wxWidgets/wxWidgets#22629]
When refreshing part of a window, such as a wxTreeCtrl or wxListCtrl, especially within focus events the non-updated part the client area can be corrupted, which it makes it look as though text becomes bold and icons aren't draw correctly. This is new since I used 3.1.5.

To Reproduce:

Compile and run the aui sample, auidemo. Click Item 5 in the tree. Then click on the tab wxTextCtrl 2, and then wxTextCtrl 3. When the popup message is shown, you'll see the root item of the tree pane - wxAUI Project - go bold. Resizing the pane clears the problem.

This is with:
 - wxWidgets 3.2.0
 - wxOSX
 - macOS Catalina 10.15.7
 - macOS SDK 11.1

Might it be related to wxPaintDC changes? Unfortunately it happens so much in my app that it's not useable.
Thanks for any insight!

**Comment by vadz** [comment]
I'll try to debug it, but, just to be sure, is this wxAUI-specific or do you also see it without it?

Also, which `wxPaintDC` changes do you mean? I'm afraid I must have missed this. If you already know which change broke this, it would be very helpful to know it, otherwise perhaps you could try using git-bisect between 3.1.5 and 3.2.0 to find it? TIA!

**Comment by JulianSmart** [comment]
Hi Vadim, I couldn't reproduce it in the treectrl sample although maybe I wasn't persistent enough. So I think it might well be triggered by AUI.

I vaguely thought it might be related to this:

https://github.com/wxWidgets/wxWidgets/issues/19108

but only because it was a paint-related change. The bug (if it's the same one) also messes up painting in my Jutoh welcome window - it's supposed to paint shadows around the welcome window, but this is corrupted - the shadow goes enormous/semi-painted and icons are visible through the HTML welcome window.

I may well have to look into bisecting but OTOH my grasp of git is so tenuous (as ever) I'll probably chuck the Mac out of the window before I ever get to grips with that. And it's one heavy 2012 MacBook Pro.

Thanks!

**Comment by vadz** [comment]
Unfortunately I don't see this problem under my macOS system (12.0.1), so it's going to be really difficult for me to debug it. Knowing that it worked before, bisecting would really be the first thing to do, but I can't do this neither. I know you like to complain about Git but running git-bisect is a purely mechanical operation that hardly requires any knowledge of Git at all. Please have a look at its man page (`git bisect --help`) and see how simple it is. So I'm afraid that if you're looking for an excuse to upgrade your Mac, git-bisect won't give you any opportunity to chuck your old MBP out of the window. Please try it!

As an aside, if you already have higher resolution icons for the AUI bitmaps (e.g. the close one in the notebook pages) it would certainly be great if we could use them, because the current ones look pretty ugly in high DPI.

**Comment by csomor** [comment]
this might also be something related to background changes

**Comment by csomor** [comment]
@JulianSmart do you know whether this is Catalina only ?

**Comment by vadz** [comment]
I definitely think it would be useful to find the offending commit using git-bisect and it looks like a much lesser burden than shipping two different versions to me, but I had already made this argument so it's probably no use to repeat it.

Thanks for the bitmaps, they definitely look much nicer than the current ones, although I'm not sure why why are active and inactive versions identical (or at least why I don't see any difference between them), is this normal? Also, 128 versions seem just like the doubling of 64 ones, and so shouldn't be used when integrated into wx, but I think they're never going to be used anyhow in practice. Anyhow, if you ever feel like making a PR to wxAUI replacing the existing bitmaps with these ones, it surely would be a very nice improvement. If not, I'll try to do it myself one of these days...

**Comment by JulianSmart** [comment]
> @JulianSmart do you know whether this is Catalina only ?

Hi Stefan, Catalina is the latest macOS I can run on my machine so I don't know about Big Sur, but I'll have a look on the disks I have for versions prior to Catalina.
Anyway the positive thing is that we can have code that works well on older and newer macOS versions, even if they need separate builds at the moment - I'll see if I can find anything in the background code to compare between old and new wxOSX.

**Comment by JulianSmart** [comment]
Hi Vadim, sorry about the incomplete set of icons - as I recall, I didn't differentiate the inactive artwork is because I wanted a more minimalist UI with just 2 appearances per button rather than 3. Or it may have been laziness, or a bit of both.

In my art code, the disabled state is computed from active state, and for the inactive state I could have done likewise as per the default AUI artwork. In fact that probably makes more sense than providing the inactive bitmaps explicitly, so the current inactive colour is used.

**Comment by csomor** [comment]
@JulianSmart does the error already pop-up in 3.1.6 or 3.1.7 ? I've scanned through the changes, but there are so many, so any way to reduce the options would help me here ... Thanks

**Comment by whalley** [comment]
> @JulianSmart do you know whether this is Catalina only ?

I get this same issue on MacOS Ventura using wxAUI.

**Comment by codesquid** [comment]
I've ran into the same issue.

With a git bisect I've identified the following commit as introducing the regression: dc11bb18cf2ebc3f36a6d5b083a95b5639149c4f

To reproduce the issue on the latest version of macOS, I've been following these steps:
* Start auidemo
* Main Menu: View -> Create Tree
* Drag the new window so that it doesn't overlap main window
* Select last item in the newly opened tree
* Alternating clicks in the empty space below the last tree item in both the new window and the tree pane in the main window
The first item in the tree control now starts getting repainted bolder and bolder

**Comment by codesquid** [comment]
I've also tested also 3.2.0 with this patch reverted on top, it compiles fine and the issue disappears.

**Comment by vadz** [comment]
Thanks for the bisection!

@a-wi I'm probably going to revert this to fix the problem, even though I'm pretty sure that the real bug is somewhere else -- but I have no idea where, unfortunately.

**Comment by whalley** [comment]
> I've also tested also 3.2.1 with this patch reverted on top, it compiles fine and the issue disappears.

Confirmed. Works fine when the change is reverted.

**Comment by csomor** [comment]
> Thanks for the bisection!
> 
> @a-wi I'm probably going to revert this to fix the problem, even though I'm pretty sure that the real bug is somewhere else -- but I have no idea where, unfortunately.

@vadz, @a-wi yes, I'm also almost 100% sure, these bugs are a side-effect from not having the graphic state reset anymore, not something with the clipping area, but I also think that finding the true source will be quite difficult, so I'm for reverting it, but we must keep this open somewhere, so that we have some test case to come back to ...

**Comment by a-wi** [comment]
After simply reverting this commit some unit tests will likely fail because clipping region will not be reset properly in some cases.
I think an acceptable workaround could be to to use in `ResetClip()` both proper resetting with `CGContextResetClip(()` and old workaround with `CGContextRestoreGState(()`.

**Comment by vadz** [comment]
> After simply reverting this commit some unit tests will likely fail because clipping region will not be reset properly in some cases. I think an acceptable workaround could be to to use in `ResetClip()` both proper resetting with `CGContextResetClip(()` and old workaround with `CGContextRestoreGState(()`.

Yes, agreed. If you (or anybody else) could please test that this still avoids the bug, it would be great, TIA!

**Comment by a-wi** [comment]
I am unable to reproduce the issue on macOS 12. Because it's not only me (https://github.com/wxWidgets/wxWidgets/issues/22629#issuecomment-1186004689) so maybe only systems between version 10.13 and 11 are affected.
Anyway, those affected by the issue are asked to check if workaround implemented in PR #22987 helps.

**Comment by whalley** [comment]
>  so maybe only systems between version 10.13 and 11 are affected. Anyway, those affected by the issue are asked to check if workaround implemented in PR #22987 helps.

I'm on 13.0.1 and the problem occurs, though application is build with macosx-version-min=10.10 if that helps.

Will this workaround work for v13?

**Comment by a-wi** [comment]
> Will this workaround work for v13?
Now it should work for all versions.

**Comment by whalley** [comment]
@a-wi  I'm afraid this does not  fix the issue for me.

I'm reverting to this fix: https://github.com/wxWidgets/wxWidgets/issues/22629#issuecomment-1315175124 which does work.

**Comment by a-wi** [comment]
@whalley  Thanks for testing!
That's indeed a mystery that this doesn't work. It would be good to see what's is going on in the suspected ResetClip() function.
I've added some diagnostic logging to the workaround and it would be helpful if you could pull new code from PR #22987, build it in debug mode and check what is displayed on the console when you are reproducing the issue.

**Comment by whalley** [comment]
Here is your debug alongside some application debug info
[debug.zip](https://github.com/wxWidgets/wxWidgets/files/10230825/debug.zip)

**Comment by a-wi** [comment]
@whalley Thanks for testing! Debug info was really helpful. Now it's more clear where is the problem. I've implemented a fix and it would be good to check if it works any better. Could you pull recent code from PR #22987 and do testing in debug mode?

**Comment by whalley** [comment]
No change I'm afraid.
[debug2.zip](https://github.com/wxWidgets/wxWidgets/files/10239983/debug2.zip)

**Comment by a-wi** [comment]
@whalley Thanks for new data!
Now it's really a mystery. Debug log shows that clipping region restored with `CGContextResetClip`/`CGContextClipToRect` is the same as the region restored in the old way with `CGContextRestoreGState` so it's OK. So it looks there is a weird interference caused by `CGContextResetClip` but I don't know what it is.
I wonder if the issue would still be seen if you just comment out two lines (2211, 2212) in [src/osx/carbon/graphics.cpp](https://github.com/wxWidgets/wxWidgets/commit/a469f6dc9f5152a981eb9ed82172b0f2216e805e#diff-ff56edbe8091c79a61a553f62c2a240b7f4f7d6670eb35f99a790797865d2afc) with calls to `CGContextResetClip`/`CGContextClipToRect`. Could you check it?

**Comment by whalley** [comment]
@a-wi Commenting out those lines does indeed appear to get things working again with no visual issue.

**Comment by a-wi** [comment]
So it seems that the cause of the issue is `CGContextResetClip`. Beside resetting the clipping path (what it does as expected) it apparently also changes something else in `CGContext` graphics state. The problem is that documentation of this API is non-existent: https://developer.apple.com/documentation/coregraphics/2881687-cgcontextresetclip and we can only guess or find something by trial and error.
My first candidate would be font settings because the issue seems to be the related to displaying the text. Preserving font settings may be tricky but I will try to take a look at this.

**Comment by a-wi** [comment]
@whalley 
I've updated PR #22987 with code to restore the font after resetting the clip region.
Could you check if it helps?

**Comment by vadz** [comment]
Could we use `CGContext{Save,Restore}GState()` instead of using this function here? I.e. have some `m_cgClipContext` in addition to `m_cgContext` that we already use?

**Comment by a-wi** [comment]
We can use `CGSave/RestoreGState` functions, and this is actually done in the emulated version of `ResetClip()`, but with this approach resetting the clipping region will not work for some cases - like this one covered by RegionsAndPushPopState test (https://github.com/wxWidgets/wxWidgets/blob/b47c46a8d79e0486ffabd0ec24c8934ec87b3aba/tests/graphics/clippingbox.cpp#L4591).
With `CGContextResetClip` resetting would always work.

**Comment by whalley** [comment]
> @whalley
> I've updated PR #22987 with code to restore the font after resetting the clip region.
> Could you check if it helps?

Unfortunately it does not help.

**Comment by vadz** [comment]
> We can use `CGSave/RestoreGState` functions, and this is actually done in the emulated version of `ResetClip()`, but with this approach resetting the clipping region will not work for some cases - like this one covered by RegionsAndPushPopState test

FWIW I don't think it's a good idea to mix the calls to `ResetClip()` and `PopState()` as this test does. If we can avoid the problem by documenting that these functions shouldn't be used together, I'd be perfectly fine with doing it.

**Comment by a-wi** [comment]
I think clipping path/region is the same graphics context attribute like any other and any clipping-related operations are legitimate also in this specific case with Pop/PushState() calls. If we allow changing font, line width, colors, etc. in such scenario we should allow also resetting the clip region. 
Test covering this scenario works with no hacks for all other ports so this feature is not exceptional. Even for `wxOSX` it works fine with dedicated `CGContextResetClip` API - only emulated version of `ResetClip()` fails.
At the moment I would not give up and left the test as it is. I think that with regards to testing our general problem (not only for clipping) are not too aggressive tests but insufficient number of automated tests.
The problem here are not yet determined side effects of `CGContextResetClip` and unfortunately this is not reproducible (so far) in any structured test what makes bug fixing very hard and this is the issue.
I will try to dig more (thanks to @whalley for cooperation in testing) but if I (or someone else) will not find anything to mitigate the problem we will have of course switch back to emulated version.

**Comment by a-wi** [comment]
@whalley
I've updated PR #22987 with new code. Now more graphics parameters are restored after resetting the clip region.
Could you check if it helps?

**Comment by whalley** [comment]
Tested, the issue still persists....

**Comment by a-wi** [comment]
@whalley
Let's try with latest changes in PR #22987. Practically all graphics context state parameters are restored. Let's see how it works. If it doesn't help, could you make a screenshot of affected control? Maybe also screenshot in a proper state for comparison.

**Comment by whalley** [comment]
It's still not right.

This is how it should look....
![CleanShot 2022-12-21 at 20 04 28](https://user-images.githubusercontent.com/487345/208994398-240421fe-630b-40aa-9237-1dce464520e3.png)

This is how it looks with your latest changes
![CleanShot 2022-12-21 at 20 03 56](https://user-images.githubusercontent.com/487345/208994448-8cc43fc8-a841-4949-b890-2c76bacd2466.png)

**Comment by a-wi** [comment]
@whalley It's pity nothing works. Practically all graphics state parameters are restored and it's for nothing.  It's really strange. Probably it will be necessary to resign from real resetting the clip region and use emulator instead.
So the visual issue is that text and icons are blurred, right? Is it seen in HiDPI mode? What is the control? wxListCtrl? Icons on the toolbar don't seem to be affected. Is that true?

**Comment by whalley** [comment]
Issue does seem to be restricted to Text.

The exampls shown is a wxTreeCtrl but the same issue occurs with the text in wxListCtrl's.

**Comment by a-wi** [comment]
@whalley Are you able to reproduce this issue with treectrl sample (https://github.com/wxWidgets/wxWidgets/tree/master/samples/treectrl)?

**Comment by a-wi** [comment]
I think I've found a workaround for the issue with drawing `wxTreeCtrl`. It's implemented in PR #22987.  
 @whalley, @codesquid Could you check if it works for you?

**Comment by a-wi** [comment]
I found a way to reproduce this issue with modified minimal sample. When patched minimal sample is running, one need to alternate its focus by clicking once on the sample window once on the another window. It's seen that every cycle the text is displayed as more and more bold (drawn line is unaffected).
![Screenshot_1](https://user-images.githubusercontent.com/7330332/213928237-4b8bf196-8c0a-4a7a-839c-87b9273bff1e.png)
![Screenshot_2](https://user-images.githubusercontent.com/7330332/213928245-aa584126-e0e8-4a7a-9ae5-4f8f80d63871.png)
![Screenshot_3](https://user-images.githubusercontent.com/7330332/213928248-854dd054-4847-4f67-a9f3-d2daf4d7a98a.png)

It seems the offender is `CGContextResetClip()` native API (used in `wxMacCoreGraphicsContext::ResetClip()`through `wxDC::DestroyClippingRegion()`). It resets the clipping region as expected, but also apparently changes the state of graphics context in such a way that further text drawing operations are affected. What exactly is changed is hard to tell at the moment - publicly available graphics state parameters seem to be the same at every painting cycle.
It looks that until the cause of weird `CGContextResetClip()` interferences is determined it shouldn't be used. So probably `wxMacCoreGraphicsContext::ResetClip()` would need to be rolled-back to also far from perfect emulated version with `GContextRestoreGState()/CGContextSaveGState()`.

```diff --git a/samples/minimal/minimal.cpp b/samples/minimal/minimal.cpp
--- a/samples/minimal/minimal.cpp
+++ b/samples/minimal/minimal.cpp
@@ -137,6 +137,51 @@ bool MyApp::OnInit()
 // main frame
 // ----------------------------------------------------------------------------
 
+#include "wx/osx/private.h"
+
+class TestControl : public wxControl
+{
+public:
+    TestControl(wxWindow* parent, const wxSize& size)
+        : wxControl(parent, wxID_ANY, wxDefaultPosition, size)
+    {
+        Bind(wxEVT_PAINT, &TestControl::OnPaint, this);
+    }
+
+    void OnPaint(wxPaintEvent&)
+    {
+        static int n = 0;
+        wxLogDebug("Paint %i", ++n);
+
+        wxPaintDC dc(this);
+
+        wxGraphicsContext* gc = dc.GetGraphicsContext();
+        CGContextRef cg = (CGContextRef)gc->GetNativeContext();
+
+//        dc.SetClippingRegion(10, 0, 100, 15);
+//        dc.DestroyClippingRegion();
+        CGContextResetClip(cg);
+#if false
+        CGAffineTransform tm = CGContextGetTextMatrix(cg);
+        wxLogDebug("Text matrix %g %g %g %g %g %g", tm.a, tm.b, tm.c, tm.d, tm.tx, tm.ty);
+        CGAffineTransform udt = CGContextGetUserSpaceToDeviceSpaceTransform(cg);
+        wxLogDebug("User/Dev matrix %g %g %g %g %g %g", udt.a, udt.b, udt.c, udt.d, udt.tx, udt.ty);
+        CGAffineTransform ctm = CGContextGetCTM(cg);
+        wxLogDebug("CTM %g %g %g %g %g %g", ctm.a, ctm.b, ctm.c, ctm.d, ctm.tx, ctm.ty);
+        CGRect cr = CGContextGetClipBoundingBox(cg);
+        wxLogDebug("Clip %g,%g %gx%g", cr.origin.x, cr.origin.y, cr.size.width, cr.size.height);
+        CGInterpolationQuality iq = CGContextGetInterpolationQuality(cg);
+        wxLogDebug("Interp. quality %i", iq);
+        CGPoint tp = CGContextGetTextPosition(cg);
+        wxLogDebug("Text pos. %g,%g", tp.x, tp.y);
+        CGPoint cp = CGContextGetPathCurrentPoint(cg);
+        wxLogDebug("Path cur. point %g,%g", cp.x, cp.y);
+#endif
+        dc.DrawText("abcd", 10, 0);
+        dc.DrawLine(25, 30, 25, 60);
+    }
+};
+
 // frame constructor
 MyFrame::MyFrame(const wxString& title)
        : wxFrame(NULL, wxID_ANY, title)
@@ -175,6 +220,13 @@ MyFrame::MyFrame(const wxString& title)
     CreateStatusBar(2);
     SetStatusText("Welcome to wxWidgets!");
 #endif // wxUSE_STATUSBAR
+    wxSizer* sizer = new wxBoxSizer(wxHORIZONTAL);
+    TestControl* ctrl = new TestControl(this, wxSize(200, 200));
+    wxTextCtrl* tc = new wxTextCtrl(this, wxID_ANY, "1234");
+    sizer->Add(ctrl);
+    sizer->Add(tc);
+    SetSizer(sizer);
+    ctrl->SetFocus();
 }
 
 
```

**Comment by csomor** [comment]
@a-wi in order for me to reproduce this with your modified minimal sample, I have to click into the TestControl and then into wxTextCtrl with the current state of master on which macOS ?

**Comment by a-wi** [comment]
TextCtrl is here just for comparison. You need to switch between test window and any other window. Tested on Ventura.

**Comment by a-wi** [comment]
@csomor And while testing I've found that if antialiasing is disabled (either by `dc.GetGraphicsContext()->SetAntialiasMode(wxANTIALIAS_NONE)` or `CGContextSetAllowsAntialiasing(cg, false)`) the issue doesn't occur.

**Comment by csomor** [comment]
@a-wi thanks, on my 13.2 I can reproduce things (as long as my have my glasses on 😂). So it's great to have such a simple test case. Thanks a lot.
I have the impression that rendering pipeline somehow gets changed as well with `CGContextResetClip`, so that things get overdrawn while they do not get overdrawn with the old code, fixing that artefact is easy by using a CGContextClearRect but of course this is not the proper fix. It may well be that the issue is somewhere completely different. I'll try to debug the redraw cycle with the current macOS versions.

**Comment by csomor** [comment]
I see that in `wxWidgetCocoaImpl::drawRect` the context we are getting from the OS for drawing is already clipped, to the TestControl bounds, now if I do a `CGContextResetClip` this results in the GraphicsContext to get clipped only at the bounds of the Frame. Which means many operations will be too wide and redraw artifacts happen. I have not found a way to retrieve the true clipping area, only the bounds which is not sufficient for storing and restoring ...

**Comment by a-wi** [comment]
If `CGContextResetClip` doesn't reset to the clipping region that we have on entry to `drawRect` but resets it absolutely (i.e. to the parent's bounds) it means it rather useless.
So we could make use of `CGContextResetClip` if we only could save/restore non-rectangular clipping region on entry to `drawRect`. I don't know how to do this in an elegant way. Not very elegant option is to save/restore entire CG context state what has some side-effects to `wxGraphicsContext` because it may interfere with explicit calls to `PushState/PopState` - https://github.com/wxWidgets/wxWidgets/blob/b91be88c0b5342a65f088fa1f3fdf83de7ebb5af/tests/graphics/clippingbox.cpp#L4676. It looks CG API doesn't offer any support for maintaining (retrieving, saving) non-rectangular clipping areas so there is no good way to fix this issue. Ugly workaround with push/pop state seems to be the only option. Pity.

**Comment by vadz** [comment]
Sorry, but what are we going to do for 3.2.2 here finally?

**Comment by csomor** [comment]
@vadz I think we have to revert this for 3.2.2 and then look for other ways to fix the original problem.

**Comment by vadz** [comment]
@a-wi Would you prefer to do this yourself (if you agree that it's the only thing to do) or should I?

**Comment by a-wi** [comment]
Workaround applied in 6674ce7fe6f8407b077350105bfb4ef0d3658c41

**Comment by vadz** [comment]
Thanks, I've also created a PR to revert this in 3.2, please let me know if you see anything wrong with this.

Once that PR is merged, I think this issue can be closed as there doesn't seem to be anything to be done here, is there?

**Comment by csomor** [comment]
> Once that PR is merged, I think this issue can be closed as there doesn't seem to be anything to be done here, is there?

we have to reopen the issues that were fixed by original commit, I've found #19108, I'll try to look at what I can do within the 'old' implementation, is anyone aware of other bugs that were fixed by this which we have to reopen again ?

**Comment by a-wi** [comment]
I think the issue directly related to the problem with resetting the clip is #19231. The goal should be also to re-enable a unit test for macOS > 10.12 - https://github.com/wxWidgets/wxWidgets https://github.com/wxWidgets/wxWidgets/blob/6674ce7fe6f8407b077350105bfb4ef0d3658c41/tests/graphics/clippingbox.cpp#L4694

**Comment by csomor** [comment]
@a-wi thanks :-)

**Comment by vadz** [comment]
The commit above should have fixed this for 3.2.2, so closing.
