### ISSUE TITLE
Enhancement: Make wxGTK the default port on Haiku

### ISSUE THREAD

**Issue by generic-pers0n** [wxWidgets/wxWidgets#25676]
### Description
Originally, when Haiku support was first merged in wxWidgets, it built the wxQt port by default. As according to [this closed issue](https://github.com/wxWidgets/wxWidgets/issues/9168#issuecomment-1010662239), wxWidgets ran under Haiku via wxQt. Therefore, the default port to build on Haiku was wxQt since it worked there.

However, a lot has changed since that decision was made. Now, wxGTK works, albeit with some [trivial patches](https://github.com/haikuports/haikuports/blob/master/x11-libs/wxgtk/patches/wxgtk-3.2.6.patchset), on Haiku through a Wayland compatibility layer. This enables programs like [Tenacity](https://depot.haiku-os.org/#!/pkg/tenacity/haikuports/haikuports_x86_64/1/3/3/-/5/x86_64?bcguid=bc234-FHYG) to work on Haiku with minimal, if any at all, issues.

Given the stability that wxGTK has, I propose making it the default for Haiku. This will allow for more programs to run natively on Haiku out of the box. In doing so, I also propose partially upstreaming [this patchset](https://github.com/haikuports/haikuports/blob/master/x11-libs/wxgtk/patches/wxgtk-3.2.6.patchset) as well, though I'd also want to discuss that with the original authors first. (Note that the main patch of interest is the second one in this set; the first one, from what I can tell, appears to be not needed anymore). Should all go well, we should see a pull request opened to resolve this issue.

**Comment by vadz** [comment]
The last time I had looked at Haiku was in 199? when I got my BeOS CD (floppies?) and wanted to write wxBeOS port using its native API), so I have no idea whether GTK or Qt is a better target for it nowadays. Does anybody (else) have any thoughts about which toolkit should be used there?

If not, i.e. nobody objects, I don't mind switching to wxGTK by default (it's not a big deal to select wxQt if this is what is needed).

**Comment by generic-pers0n** [comment]
> The last time I had looked at Haiku was in 199? when I got my BeOS CD (floppies?) and wanted to write wxBeOS port using its native API), so I have no idea whether GTK or Qt is a better target for it nowadays. Does anybody (else) have any thoughts about which toolkit should be used there?

Wow! That's quite some history!

I do have some thoughts on the toolkit we should use. In fact, I've been wanting to write a wxHaiku port that would also use its native API. Personally, I would prefer it to use the native API to avoid any compatibility layers whatsoever. Alas, that takes some time and using another already existing port that can work on Haiku will be a good compromise until there's a wxHaiku port up and ready.

If the wxBeOS port exists anywhere, I will be interested in making it work on Haiku. It may require a bit of effort, but I will be interested in getting it to run on modern Haiku.

> If not, i.e. nobody objects, I don't mind switching to wxGTK by default (it's not a big deal to select wxQt if this is what is needed).

Nothing to say except great!

**Comment by vadz** [comment]
> If the wxBeOS port exists anywhere

I don't think it ever existed beyond some _very_ basic functionality (like a TLW with a button). And I guess what was there got lost in the pre-VCS days, as the only commit mentioning BeOS in wx that I can find is b12915c104 (1. wxBase compiles under BeOS 2. several bugs corrected in wxTextCtrl::Load/SaveFile (wxMSW), 1999-12-22), i.e. for non-GUI parts only. AFAIR there were some big problems between BeOS API model (which was pretty revolutionary at the time) and wx API model that I didn't know how to resolve. But this was a really long time ago and I forgot many much more recent things...

**Comment by generic-pers0n** [comment]
> > If the wxBeOS port exists anywhere
> 
> I don't think it ever existed beyond some _very_ basic functionality (like a TLW with a button). And I guess what was there got lost in the pre-VCS days, as the only commit mentioning BeOS in wx that I can find is b12915c104 (1. wxBase compiles under BeOS 2. several bugs corrected in wxTextCtrl::Load/SaveFile (wxMSW), 1999-12-22), i.e. for non-GUI parts only. AFAIR there were some big problems between BeOS API model (which was pretty revolutionary at the time) and wx API model that I didn't know how to resolve. But this was a really long time ago and I forgot many much more recent things...

I suppose nothing fundamental has changed since then (i.e., for the BeOS API), but I'll still see how we can get wxWidgets to fit on top of the BeOS API. It could be easier nowadays, or it may not be. I can never say since I never got the chance to see wxWidgets evolve from that point.

Either way, for such a new port, I feel a good place to begin is with non-GUI classes, but that's out of the scope of this issue.
